### ISSUE TITLE
How to do multiple sort fields?

### ISSUE THREAD

**Issue by rohmanhm** [gobeam/mongo-go-pagination#10]
We can have a single sort by using `.Sort("price", -1)`.
But how to add another sort field?

I tried `.Sort("price", -1).Sort("_id", 1)` didn't work.

Thanks

**Comment by rohmanhm** [comment]
And still, make the pagination works.

**Comment by gobeam** [comment]
Currently I haven't added any support for multiple sorts but I will surely consider adding it.

**Comment by gobeam** [comment]
> We can have a single sort by using `.Sort("price", -1)`.
> But how to add another sort field?
> 
> I tried `.Sort("price", -1).Sort("_id", 1)` didn't work.
> 
> Thanks

I've added the featured check it on [v0.0.3](https://github.com/gobeam/mongo-go-pagination/tree/v0.0.3)

**Comment by rohmanhm** [comment]
Wow awesome, Thanks @gobeam 🎉
