### ISSUE TITLE
Is there any way to sort by weight(score) for full text search fields?

### ISSUE THREAD

**Issue by dmitrypro77** [gobeam/mongo-go-pagination#17]
**Is your feature request related to a problem? Please describe.**
As I know right now we have only .Sort() method which accept 2 arguments: field name and sort by ASC, DESC but it would be nice to have a method to sort by score(weight) for full text search fields. The query might be something like:
`db.table.find({$text:{$search:"Test"}},{score:{$meta:"textScore"}}).sort({score:{$meta:"textScore"}})`

**Describe the solution you'd like**
It would be nice to have a method like .sortByScore()

**Comment by gobeam** [comment]
> **Is your feature request related to a problem? Please describe.**
> As I know right now we have only .Sort() method which accept 2 arguments: field name and sort by ASC, DESC but it would be nice to have a method to sort by score(weight) for full text search fields. The query might be something like:
> `db.table.find({$text:{$search:"Test"}},{score:{$meta:"textScore"}}).sort({score:{$meta:"textScore"}})`
> 
> **Describe the solution you'd like**
> It would be nice to have a method like .sortByScore()

In branch [sort_feature_change](https://github.com/gobeam/mongo-go-pagination/tree/sort_feature_change) I've changed Sort 2nd argument to type interface can you checkout on that branch and test the solution.
```go
sortValue := bson.M{
		"$meta" : "textScore",
	}
aggPaginatedData, err := paginate.New(collection).Context(ctx).Limit(limit).Page(page).Sort("score", sortValue)...
```
I've tested it but still, I want to make sure the solution works for you then we can merge it on the main branch.

**Comment by dmitrypro77** [comment]
@gobeam Works Perfect now! Thank you so much for your quick turnaround. Great Library and implementation!

**Comment by gobeam** [comment]
> @gobeam Works Perfect now! Thank you so much for your quick turnaround. Great Library and implementation!

You're welcome. Happy to know you liked it. I'm closing this issue now.
