### ISSUE TITLE
getSkip logic is broken

### ISSUE THREAD

**Issue by ghstahl** [gobeam/mongo-go-pagination#19]
**Describe the bug**

## The Problem  

[getSkip](https://github.com/gobeam/mongo-go-pagination/blob/c8399f4ab4ce4b944e60fcaaba8e393e7b129bff/pagingQuery.go#L265)

 ```go
func getSkip(page, limit int64) int64 {	
  page--	
  skip := page * limit	
  skip--
  if skip <= 0 {		
     skip = 0	
  }
return skip
}
```
if ```page == 2``` and ```limit == 1```
then  the following should be returned.

skip == 1

Actual: skip == 0

## The fix  
 ```go
func getSkip(page, limit int64) int64 {	
  page--	
  skip := page * limit	
   
  if skip <= 0 {		
     skip = 0	
  }
return skip
}
```

The current code will produce the same result given the following paging arguments.
```
page = 1
limit = 1
 and
page = 2
limit = 1
```

**Comment by gobeam** [comment]
@ghstahl thank you for pointing this out, seems like the new changes that was merged was culprit old code was working well too. I agree to merge your pull request #20 but can you make cover more on written test seems like there is some issue on coverage. Thank you!
