### ISSUE TITLE
Skip calculation error

### ISSUE THREAD

**Issue by a97077088** [gobeam/mongo-go-pagination#21]
**Describe the bug**

**To Reproduce**
1. Call function '...'
mongopagination.New(models.RedPackCollection).Context(context.TODO()).Limit(int64(p.PageSize)).Page(int64(p.CurPage)).Filter()
2. Pass value '...'
p.PageSize=10
p.CurPage=2
3. See error

func getSkip(page, limit int64) int64 {
	page--
	skip := page * limit
	skip--  / / produces an extra result

	if skip <= 0 {
		skip = 0
	}

	return skip
}

**Expected behavior**

I think we should delete him

**Screenshots**

**Additional context**

**Comment by gobeam** [comment]
Hello @a97077088  it is working as expected may be you're using old version? Please test it from example folder which I have added recently.

**Comment by a97077088** [comment]
Correctly, these mistakes re-0.05, after renewal, other work styles, thanks
