### ISSUE TITLE
Duplicate element at page 2 in v0.0.5

### ISSUE THREAD

**Issue by johnhoonline** [gobeam/mongo-go-pagination#23]

**Comment by gobeam** [comment]
Can you reconfirm the issue by running example of v0.0.5. There is no issue in current version, may be you're using old version. Thanks.

**Comment by johnhoonline** [comment]
Something was wrong with updates?
<img width="793" alt="Screen Shot 2021-06-30 at 11 52 21 AM" src="https://user-images.githubusercontent.com/86702835/123915401-ab81a480-d9aa-11eb-9ba6-7584b9ea4bb6.png">

**Comment by gobeam** [comment]
> Something was wrong with updates?
> <img alt="Screen Shot 2021-06-30 at 11 52 21 AM" width="793" src="https://user-images.githubusercontent.com/86702835/123915401-ab81a480-d9aa-11eb-9ba6-7584b9ea4bb6.png">

Have you tested using latest release?

**Comment by johnhoonline** [comment]
Yes, I've tested in v0.0.5. My question is why `skip--` at line 268?

**Comment by gobeam** [comment]
it was previous wrong code that was merged.
Current implementation: 
```go
func getSkip(page, limit int64) int64 {
	page--
	skip := page * limit

	if skip <= 0 {
		skip = 0
	}

	return skip
}
```

**Comment by gobeam** [comment]
There is no issue with current version so I'm closing the issue now, if you have any further issue you can reopen the issue. Thanks.

**Comment by gobeam** [comment]
My bad only master branch was updated seems like I forgot to push latest release so v0.0.5 was stale, can you check on latest release v0.0.6. Thanks.
