### ISSUE TITLE
getSkip decrements skip by one more, causing the pagination to pick up one less document

### ISSUE THREAD

**Issue by lemorian** [gobeam/mongo-go-pagination#24]
**Describe the bug**
"**getSkip**" function decrements skip by one more, causing the pagination to pick up one less document.

**To Reproduce**
Create a collection with 2 documents;
1. Call pagination function with page number 2 and limit 1.
2. The function returns the first document instead of second document.

**Expected behavior**
The function should return second document in page 2.

**Additional context**
This happens in version v0.0.5 where the "**getSkip**" function decrements the "**skip**" value by one more after calculating the correct value.

// getSkip return calculated skip value for query
```
func getSkip(page, limit int64) int64 {
	page--
	skip := page * limit
	skip--

	if skip <= 0 {
		skip = 0
	}

	return skip
}
```

**Comment by gobeam** [comment]
My bad only master branch was updated seems like I forgot to push latest release, can you check on latest release v0.0.6. Thanks.

**Comment by lemorian** [comment]
Thank you for the very quick response!
