### ISSUE TITLE
Allow to disable pagination

### ISSUE THREAD

**Issue by ahmedfaragngoco** [gobeam/mongo-go-pagination#32]
**Is your feature request related to a problem? Please describe.**
How can i disable the pagination? When i tried to not chain the limit and page, i got an error says "page or limit cannot be less than 0"

**Describe the solution you'd like**
Like this NPM (JS) package [here](https://www.npmjs.com/package/mongoose-paginate-v2), there is an option "pagination"  if it is set to false, it will return all docs without adding limit condition. (Default: True)

**Comment by gobeam** [comment]
@ahmedfaragngoco this package was developed for pagination purposes, so I think adding this feature will not serve any purpose because you can use normal queries to get data without pagination.
