### ISSUE TITLE
Hardcoded Sort on Aggregate function

### ISSUE THREAD

**Issue by Wiandono** [gobeam/mongo-go-pagination#4]
```go
facet := bson.M{"$facet": bson.M{
		"data": []bson.M{
			{"$sort": bson.M{"createdAt": -1}},
			{"$skip": skip},
			{"$limit": paging.LimitCount},
		},
		"total": []bson.M{{"$count": "count"}},
	},
}
```

It makes it impossible to have a sort pipeline when doing aggregation

**Comment by gobeam** [comment]
@Wiandono I have pushed changes please pull again and check now, I've implemented chaining Sort, hope this helps.

**Comment by Wiandono** [comment]
Thank you very much for the enhancement! :bow:
