### ISSUE TITLE
OffSet Usage

### ISSUE THREAD

**Issue by lukekhamilton** [gobeam/mongo-go-pagination#5]
Hey is it possible to use or add the usage of an OffSet at all? 

```
aggPaginatedData, err := New(collection).Limit(limit).OffSet(offset).Sort("price", -1).Aggregate(match, projectQuery)
...

```

**Comment by gobeam** [comment]
@lukekhamilton  If you pass page offset will be automatically calculated for you and if you don't pass page it will assume you are querying first page so anyways offset will be calculated for you so you don't have to do any calculation by yourself. Hope you like the package don't forget to star it. Thanks.
