### ISSUE TITLE
Aggregate with facet is ignoring indexes and taking more time in execution of query. Can we rewrite aggregate without facet and still support pagination?

### ISSUE THREAD

**Issue by lalithabandaru** [gobeam/mongo-go-pagination#6]
Aggregate with facet is ignoring indexes and taking more time in execution of query. Can we rewrite aggregate without facet and still support pagination

**Comment by gobeam** [comment]
I would certainly want to see if I can do that when I'm free, but if you think you have some ideas feel free to make changes and do pull request.
