### ISSUE TITLE
decode to struct we want instead of bson.raw

### ISSUE THREAD

**Issue by FaRzad-845** [gobeam/mongo-go-pagination#9]
in [line ](https://github.com/gobeam/mongo-go-pagination/blob/5f989e4d81b251e2dfff375f9a8a7f8c8e59a98e/pagingQuery.go#L211), you use a decoder and pass variable in type of bson.raw, in the example you use decode again to convert data to struct we want ... 
in my opinion we can add func to app to get the struct and decode it in the first time ! what is your opinion about this ?

**Comment by gobeam** [comment]
> in my opinion we can add func to app to get the struct and decode it in the first time ! what is your opinion about this ?

Sure it will be nice addition, I will surely try to add it during my free time.

**Comment by gobeam** [comment]
> in [line ](https://github.com/gobeam/mongo-go-pagination/blob/5f989e4d81b251e2dfff375f9a8a7f8c8e59a98e/pagingQuery.go#L211), you use a decoder and pass variable in type of bson.raw, in the example you use decode again to convert data to struct we want ...
> in my opinion we can add func to app to get the struct and decode it in the first time ! what is your opinion about this ?

 I've added the feature for normal queries in latest release hope you like it.
